### ISSUE TITLE
multiGesturemexample js version

### ISSUE THREAD

**Issue by bluelemonade** [vueuse/gesture#2]
hi,

would be great if you could provide a js version of the multigesture ts version. I couldn‘t get the ts version to work.

thank you.

**Comment by Tahul** [comment]
Hello 😄,

Sorry for the late answer, has been pretty busy lately.

Could you maybe explain precisely what can't you get to work?

The multigesture example can be found [here](https://github.com/vueuse/gesture/tree/main/demo) and is still the example I use to debug this package.

It works perfectly fine for me lately, so feel free to reopen this issue if needed.
