### ISSUE TITLE
TypeError: mixerFactory is not a function

### ISSUE THREAD

**Issue by prpanto** [vueuse/gesture#27]
I use the code from the [demo](https://github.com/vueuse/gesture/blob/main/demo/src/components/Joystick.vue) and I have error `mixerFactory is not a function`

**Comment by KamilStehlicek** [comment]
That is a wrong demo code. You want to use this
```
const { motionProperties } = useMotionProperties(domElementRef, {
  cursor: 'grab',
  x: 0,
  y: 0
})

const { set } = useSpring(motionProperties, {
  damping: 50,
  stiffness: 220,
})
```
