### ISSUE TITLE
Limit drag to horizontal?

### ISSUE THREAD

**Issue by mesqueeb** [vueuse/gesture#5]
I was wondering if it's possible to limit the drag to horizontal?

**Comment by patchthecode** [comment]
yes.

```
axis: 'y',
```

**Comment by mesqueeb** [comment]
@patchthecode is it possible to add 2 extra examples to the live docs?
1. dragging limited horizontally
2. dragging limited vertically

I'd love to play around with that on mobile safari to see how smooth it is.
